# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: hennr.name
email: hennr@hennr.name
description: > # empty

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hennr.name" # the base hostname & protocol for your site
github_username:  hennr

# Build settings
markdown: kramdown
